version: '3'
services:
  mysql:
    image: mysql:8-oracle
    container_name: sesohaeng_database_container
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sesohaeng