spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/sesohaeng?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
    # OAuth2의 기본 redirectUri는 /login/oauth2/code/{provider} 입니다
    # ex) /login/oauth2/code/google
    # 기본 redirectUri를 그대로 사용할 때는 특별한 설정이 필요 없지만 변경하고 싶으면 application.yml에 명시해야 합니다
  profiles:
    include: oauth

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 693007930110-5u66i5c992figci0e3oh3n53sm8q6hb7.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "http://localhost:8080/oauth2/callback/google"
            scope:
              - email
              - profile
app:
  auth:
    token:
      secret-key: "sesohaengjwtsecretkey"
      refresh-cookie-key: "refresh"
  oauth2:
    # OAuth2 공급자로 성공적으로 인증 한 후 사용자에 대한 인증 토큰을 생성하고 토큰을
    # 프론트 엔드 클라이언트가 /oauth2/authorize 요청에서 지정한 redirectUri입니다.
    # 쿠키는 모바일 클라이언트에서 잘 작동하지 않기 때문에 사용하지 않습니다.
    authorizedRedirectUri: "http://localhost:3000/oauth2/redirect"
